# Generated by Django 3.1 on 2020-10-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('img01', models.ImageField(blank=True, upload_to='')),
                ('img02', models.ImageField(blank=True, upload_to='')),
                ('img03', models.ImageField(blank=True, upload_to='')),
                ('img04', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='images',
            name='files',
            field=models.FileField(blank=True, upload_to='multi_imgs/'),
        ),
    ]
