# Generated by Django 3.1 on 2020-10-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_users_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='DMs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm_from_name', models.CharField(max_length=255)),
                ('dm_from_email', models.CharField(max_length=255)),
                ('dm_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dm_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm', to='login.users')),
            ],
        ),
    ]
