# Generated by Django 3.1 on 2020-10-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201014_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='dms',
            name='if_check',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
